name: nightly benches

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'

jobs:
  swim:
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: swim
      n_runs: 16
      run_time_s: 1200
      cpu_tag: 7950X

  trousers:
    needs: swim
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: trousers
      n_runs: 16
      run_time_s: 1200
      cpu_tag: 7950X

  shirts:
    needs: trousers
    uses: ./.github/workflows/single_bench.yml
    with:
      instance: shirts
      n_runs: 16
      run_time_s: 1200
      cpu_tag: 7950X
