name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests (no SIMD)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-targets

  tests-simd:
    name: Run tests (SIMD)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --all-targets --features=simd

